targets:
  $default:
    sources:
      - $package$
      - lib/**
      - web/**
      - pubspec.yaml
    builders:
      build_web_compilers:entrypoint:
        generate_for:
          - web/**.dart
        options:
          compiler: dart2js
          dart2js_args:
            - -O2
            - --fast-startup
            - --minify
            - --trust-primitives
            - --trust-type-annotations
            - -DTITLE=@PlugFox
      #json_serializable:
      #  enabled: true
      #  generate_for:
      #    exclude:
      #      - test
      #    include:
      #      - lib/**
      #  options:
      #    any_map: false
      #    checked: false
      #    create_factory: true
      #    create_to_json: true
      #    disallow_unrecognized_keys: false
      #    explicit_to_json: false
      #    field_rename: none
      #    ignore_unannotated: false
      #    include_if_null: true
      #freezed:
      #  enabled: true
      #  generate_for:
      #    exclude:
      #      - test
      #    include:
      #      - lib/**
      #built_value_generator|built_value:
      #  enabled: true
      #  generate_for:
      #    exclude:
      #      - test
      #    include:
      #      - lib/**
      #retrofit:
      #  enabled: true
      #  generate_for:
      #    exclude:
      #      - test
      #    include:
      #      - lib/**
      #pubspec_generator:
      #  options:
      #    output: lib/src/app/common/constant/pubspec.yaml.g.dart
      # https://moor.simonbinder.eu/docs/advanced-features/builder_options/
      #moor_generator:
      #  generate_for:
      #    exclude:
      #      - test
      #      - lib
      #      - graphql
      #    include:
      #      - lib/src/app/common/database/**
      #  options:
      #    compact_query_methods: true
      #    data_class_to_companions: true
      #    mutable_classes: false
      #hive_generator:
      #  generate_for:
      #    exclude:
      #      - test
      #      - lib
      #      - graphql
      #    include:
      #      - lib/src/features/background_service/data/models/location_data.dart

builders:
  #freezed:
  #  import: "package:freezed/builder.dart"
  #  builder_factories: ["freezed"]
  #  build_extensions: { ".dart": [".freezed.dart"] }
  #  auto_apply: dependents
  #  build_to: source
  #  runs_before: ["json_serializable|json_serializable"]
  #built_value:
  #  target: ":built_value_generator"
  #  import: "package:built_value_generator/builder.dart"
  #  builder_factories: ["builtValue"]
  #  build_extensions: {".dart": [".built_value.g.part"]}
  #  auto_apply: dependents
  #  build_to: cache
  #  applies_builders: ["source_gen|combining_builder"]